export type Collection = "projects" | "contributions";

export type PortfolioEntry = {
  id: string;
  name: string;
  summary: string;
  description: string;
  technologies: string[];
  highlights: string[];
  icon: "compass_16" | "paper";
  url: string;
} & (
  | { kind: "project" }
  | { kind: "contribution"; pullRequest: number; mergedOn: string }
);

export const portfolio: Record<Collection, readonly PortfolioEntry[]> = {
  projects: [
    {
      id: "earthquake-monitor",
      kind: "project",
      name: "Earthquake Monitor",
      summary: "Earthquake dashboard using USGS data.",
      description: "A dashboard backed by a stored earthquake history, with a map, filters, and analytics for exploring USGS events.",
      technologies: ["Java", "Spring Boot", "PostgreSQL", "React", "TypeScript"],
      highlights: [
        "Scheduled feed ingestion and historical catch-up.",
        "Database filters, pagination, and aggregate analytics.",
        "Interactive map, depth view, and pipeline health indicators.",
      ],
      icon: "compass_16",
      url: "https://github.com/noor-ahmadi/earthquake-monitor",
    },
    {
      id: "mortgage-lending-analysis",
      kind: "project",
      name: "Mortgage Lending Analysis",
      summary: "Atlanta mortgage outcomes using HMDA data.",
      description: "A reproducible explorer for mortgage application outcomes in Greater Atlanta using public HMDA data. It compares demographic outcomes within shared lenders and counties and checks financial data availability. The comparisons are descriptive.",
      technologies: ["Python", "Java", "Spring Boot", "PostgreSQL", "React", "TypeScript"],
      highlights: [
        "Filters by county, lender, and loan product.",
        "Checks how missing financial information relates to outcomes.",
        "Exports CSV data and SVG charts with source hashes and analysis settings.",
      ],
      icon: "paper",
      url: "https://github.com/noor-ahmadi/mortgage-lending-analysis",
    },
    {
      id: "internet-routing-monitor",
      kind: "project",
      name: "Internet Routing Monitor",
      summary: "Historical internet route replay. In progress.",
      description: "An internet routing investigation workspace with an interactive route diagram, animated replay, and inspectable evidence. It reconstructs Facebook's October 2021 routing changes from RIPE RIS records across three peers; live capture and backend integration are planned.",
      technologies: ["Python", "React", "TypeScript", "D3", "Vite"],
      highlights: [
        "Replays 144 archived observations from three RIPE RIS peers.",
        "Compares route changes against a reconstructed baseline.",
        "Links route selection to event history and source evidence.",
      ],
      icon: "compass_16",
      url: "https://github.com/noor-ahmadi/internet-routing-monitor",
    },
    {
      id: "vpc-networking-lab",
      kind: "project",
      name: "VPC Networking Lab",
      summary: "Linux and AWS networking lab. First release.",
      description: "A VPC lab with a public Nginx proxy, private Python app, and isolated PostgreSQL database. It implements routing and NAT with Linux namespaces and Terraform on AWS. The first release includes verified fault and repair exercises, packet captures, and a recorded demo.",
      technologies: ["Linux", "Bash", "Terraform", "AWS", "Python", "PostgreSQL"],
      highlights: [
        "Runs the proxy, app, and database across three subnet segments.",
        "Checks five Linux faults and three AWS faults with repairs.",
        "Documents packet paths, service isolation, and verified AWS teardown.",
      ],
      icon: "compass_16",
      url: "https://github.com/noor-ahmadi/vpc-networking-lab",
    },
    {
      id: "capitol-trade-watch",
      kind: "project",
      name: "Capitol Trade Watch",
      summary: "Alerts for congressional trade disclosures.",
      description: "A Python monitor that finds new House trade disclosures, reads the filing PDFs, and publishes each alert as a GitHub issue.",
      technologies: ["Python", "GitHub Actions", "pytest"],
      highlights: [
        "Reads official House filing indexes and PDFs.",
        "Tracks seen filings to avoid duplicate alerts.",
        "Supports scheduled checks and manual previews.",
      ],
      icon: "paper",
      url: "https://github.com/noor-ahmadi/capitol-trade-watch",
    },
  ],
  contributions: [
    {
      id: "pmd-7158",
      kind: "contribution",
      name: "PMD",
      summary: "Fix overload selection for parenthesized lambdas.",
      description: "Fixed PMD's Java type inference so parenthesized lambda bodies are no longer incorrectly treated as void-compatible, preventing the wrong overload from being selected.",
      technologies: ["Java", "Maven"],
      highlights: [
        "Handles explicitly and implicitly typed lambda parameters.",
        "Adds regression coverage for overloads and statement expressions.",
      ],
      icon: "paper",
      pullRequest: 7158,
      mergedOn: "2026-10-07",
      url: "https://github.com/pmd/pmd/pull/7158",
    },
    {
      id: "pmd-7138",
      kind: "contribution",
      name: "PMD",
      summary: "Reset Java duplicate-code detection state.",
      description: "Fixed a crash in PMD's Java duplicate-code detector when constructor detection state carried over from one file to the next.",
      technologies: ["Java", "Maven"],
      highlights: [
        "Starts constructor detection fresh for each source file.",
        "Adds regression coverage for crashes and misclassified identifiers.",
      ],
      icon: "paper",
      pullRequest: 7138,
      mergedOn: "2026-10-04",
      url: "https://github.com/pmd/pmd/pull/7138",
    },
    {
      id: "pmd-7130",
      kind: "contribution",
      name: "PMD",
      summary: "Show XML validation details in ruleset errors.",
      description: "Improved PMD's ruleset loading errors to include the XML location and validation reason, so callers can see what made a ruleset invalid.",
      technologies: ["Java", "Maven"],
      highlights: [
        "Preserves error summaries and excludes warnings from exceptions.",
        "Covers single, multiple, and referenced ruleset errors.",
      ],
      icon: "paper",
      pullRequest: 7130,
      mergedOn: "2026-10-04",
      url: "https://github.com/pmd/pmd/pull/7130",
    },
    {
      id: "checkstyle-21637",
      kind: "contribution",
      name: "Checkstyle",
      summary: "Check lambda names in switch expressions.",
      description: "Fixed a case where Checkstyle skipped lambda parameter names inside switch expressions, so invalid names are now reported.",
      technologies: ["Java", "Maven"],
      highlights: [
        "Distinguished switch arrows from lambda expressions.",
        "Added regression coverage for lambda forms and XPath suppression.",
      ],
      icon: "paper",
      pullRequest: 21637,
      mergedOn: "2026-09-20",
      url: "https://github.com/checkstyle/checkstyle/pull/21637",
    },
    {
      id: "opentelemetry-8775",
      kind: "contribution",
      name: "OpenTelemetry Java",
      summary: "Explain SDK type casts.",
      description: "Added the reasons behind suppressed generic-cast warnings and enabled enforcement in the shared SDK module.",
      technologies: ["Java", "Gradle"],
      highlights: [
        "Documented attribute key and value casts.",
        "Removed the module's suppression-check exemption.",
      ],
      icon: "paper",
      pullRequest: 8775,
      mergedOn: "2026-09-09",
      url: "https://github.com/open-telemetry/opentelemetry-java/pull/8775",
    },
    {
      id: "opentelemetry-8741",
      kind: "contribution",
      name: "OpenTelemetry Java",
      summary: "Require suppression explanations.",
      description: "Introduced a shared build setting requiring explanations for suppressed warnings, starting with the logging OTLP exporter.",
      technologies: ["Java", "Gradle"],
      highlights: [
        "Made the check the default for modules.",
        "Added opt outs for modules still awaiting migration.",
      ],
      icon: "paper",
      pullRequest: 8741,
      mergedOn: "2026-08-24",
      url: "https://github.com/open-telemetry/opentelemetry-java/pull/8741",
    },
    {
      id: "checkstyle-21135",
      kind: "contribution",
      name: "Checkstyle",
      summary: "Validate regexp documentation examples.",
      description: "Updated RegexpSingleline examples to quote the actual violation messages so the example tests can validate them.",
      technologies: ["Java", "Maven"],
      highlights: [
        "Corrected the messages in two examples.",
        "Removed both examples from the validation exclusion list.",
      ],
      icon: "paper",
      pullRequest: 21135,
      mergedOn: "2026-08-08",
      url: "https://github.com/checkstyle/checkstyle/pull/21135",
    },
    {
      id: "lichtfeld-1550",
      kind: "contribution",
      name: "LichtFeld Studio",
      summary: "Clarify video export code.",
      description: "Removed a helper whose name implied orientation changes even though it only made a tensor contiguous.",
      technologies: ["C++"],
      highlights: [
        "Kept the contiguous-tensor operation at the export call site.",
        "Preserved the existing frame-export behavior.",
      ],
      icon: "paper",
      pullRequest: 1550,
      mergedOn: "2026-08-03",
      url: "https://github.com/MrNeRF/LichtFeld-Studio/pull/1550",
    },
    {
      id: "transformerlens-1575",
      kind: "contribution",
      name: "TransformerLens",
      summary: "Cover deprecated model loaders.",
      description: "Added regression coverage for three deprecated model-loading paths, checking that each warning points users toward the replacement API.",
      technologies: ["Python", "pytest"],
      highlights: [
        "Checked the warning text for each legacy class.",
        "Scoped the warning filter for internal uses.",
      ],
      icon: "paper",
      pullRequest: 1575,
      mergedOn: "2026-07-31",
      url: "https://github.com/TransformerLensOrg/TransformerLens/pull/1575",
    },
    {
      id: "checkstyle-21053",
      kind: "contribution",
      name: "Checkstyle",
      summary: "Validate complexity documentation examples.",
      description: "Replaced paraphrased NPathComplexity warnings with the real messages and brought the examples into message validation.",
      technologies: ["Java", "Maven"],
      highlights: [
        "Updated two complexity examples.",
        "Removed their message-validation exemptions.",
      ],
      icon: "paper",
      pullRequest: 21053,
      mergedOn: "2026-07-31",
      url: "https://github.com/checkstyle/checkstyle/pull/21053",
    },
  ],
};
